## 1. 加载数据

In [164]:
import numpy as np
import pandas as pd

# 查看数据
train_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/sohu_train.txt', sep='\t', header=None, dtype=np.str_, encoding='utf8', names=[u'分类', u'内容'])
#train_data.loc[(train_data['分类']=='体育')|(train_data['分类']=='财经')|(train_data['分类']=='科技')]

train_data.loc[train_data['分类']=='体育']

分类                                                 内容
10000  体育  欧洲杯观察：足坛格局地震　东南欧已能占半边天 搜狐体育讯　土耳其与克罗地亚在本届欧洲杯１／４...
10001  体育  来源：搜狐体育　作者：雷欧 主队　比分　客队　进球视频青岛　１－１　武汉浙江　１－１　北京搜...
10002  体育  欧洲杯－帕夫柳琴科范尼破门　荷兰１－１俄罗斯加时 搜狐体育讯　北京时间６月２２日，２００８欧...
10003  体育  郅联璧合配合日臻完善　斯杯之前尤纳斯再谈裁员 ７年后重登上海滩，中国男篮来去匆匆。队长刘炜回...
10004  体育  盘踞世界第一逼近五百周　伍兹创造高尔夫里程碑 搜狐体育讯　下周一，老虎－伍兹将第４９９周稳坐...
...    ..                                                ...
11995  体育  《蒙牛城市之间》海选落幕　爱心融化运动舞台 搜狐体育讯　“中国，牛！”随着一张十人大合影，２...
11996  体育  扑出穆图主罚点球　布冯神勇意大利战平罗马尼亚 本报今晨２时消息（记者　张宇翔）北京时间今晨，...
11997  体育  ＂请不请希丁克＂两派争执不下　元老称借钱也要请 福拉多走了，带着惆怅和不甘，留下了一个沉重的...
11998  体育  台球天才是烹饪高手　梁文博半小时搞定四菜一汤 在斯诺克世锦赛上，梁文博闯进了八强，创造历史的...
11999  体育  为保女双晏紫混双退赛　“斗牛士”辣手摧“花” 本报记者　孙嘉晖线　梦想和现实的距离有多大，心...

[2000 rows x 2 columns]

In [165]:
train_data.loc[train_data['分类']=='财经']

分类                                                 内容
2000  财经  健全的领导力 沃伦？本尼斯最初是群体动力学（ｇｒｏｕｐ　ｄｙｎａｍｉｃｓ）最早的一批弟子之一...
2001  财经  成品油调价影响几何 编者按：国家发改委１９日宣布，６月２０日起将汽油、柴油价格每吨提高１００...
2002  财经  连阴有望终结　资深机构６月１７日推荐黑马股 新华医疗（６００５８７）是我国最大的消毒灭菌设备...
2003  财经  甘肃陇南地震亲历者口述 在５月１２日四川大地震中，甘肃省部分地市灾情严重，当地居民生活、经济...
2004  财经  深圳：一个“离经叛道”的楼市样本 张艳红编者按由于目前各地楼市处于不同的发展周期，且地缘文化...
...   ..                                                ...
3995  财经  编者按： 看到媒体登载出“‘秀水市场’末日”的文章，看着秀水市场旁边顶着秀水街的匾额虎视眈眈...
3996  财经  利尔化学招股意向书摘要 证券代码：００２２５８　证券简称：利尔化学利尔化学股份有限公司（四川...
3997  财经  辽宁成大“人造石油”　再造一个广发证券？ 广发证券是辽宁成大近年来多次转型中最成功的一笔投资...
3998  财经  财经最新动态 股票：上交所大宗交易市场开办专场业务上海证券交易所５月２８日发布并开始实施《大...
3999  财经  省部级领导言论中依法行政出现频率首超市场经济 “市场经济、依法行政、法治政府，在国务院工作报...

[2000 rows x 2 columns]

In [166]:
train_data.loc[train_data['分类']=='科技']

分类                                                 内容
8000  科技  海尔欲接盘通用家电？ 收购的成败将对海尔的发展带来举足轻重的影响。本报讯　（记者　张远惠）５...
8001  科技  陆彦玮：游戏从业人员所需素质：年轻的心＋爱玩＋敬业 国研科技简介国研信息科技有限公司（简称国...
8002  科技  网优设备商将最先受益电信重组 本报记者　张茂州酝酿已久的电信业重组终于步入实质性操作阶段。重...
8003  科技  发现号携日＂希望＂号实验舱升空　此行充满日本味 美国“发现”号航天飞机５月３１日成功发射升空...
8004  科技   赛迪网讯６月２日消息，据国外媒体报道，有分析师近日指出，为了与微软抗争，Ｇｏｏｇｌｅ必须要...
...   ..                                                ...
9995  科技  解密以色列“硅谷第二”背后发展之路 依靠高科技产业的迅猛发展，以色列近年来摆脱了国际收支赤字...
9996  科技  Ａ８音乐“逆势”上市　风投机构获数十倍回报 随着电信运营商重组的尘埃落定，国内３Ｇ时代已近在...
9997  科技   朝鲜社会科学院考古研究所的研究人员最近在黄海南道银川郡贞洞里一带发现了７０多座刻有星座坑的...
9998  科技  从一起网络“人肉搜索”事件看隐私权保护 ２００７年底，一个叫姜岩的３１岁女子，因为丈夫有了第...
9999  科技  宝利通公司于世界环境日推出“绿化企业”行动 为配合联合国世界环境日的到来，全球领先的统一协作...

[2000 rows x 2 columns]

In [167]:
train_data = train_data.loc[(train_data['分类']=='体育')|(train_data['分类']=='财经')|(train_data['分类']=='科技')]
train_data.head()

分类                                                 内容
2000  财经  健全的领导力 沃伦？本尼斯最初是群体动力学（ｇｒｏｕｐ　ｄｙｎａｍｉｃｓ）最早的一批弟子之一...
2001  财经  成品油调价影响几何 编者按：国家发改委１９日宣布，６月２０日起将汽油、柴油价格每吨提高１００...
2002  财经  连阴有望终结　资深机构６月１７日推荐黑马股 新华医疗（６００５８７）是我国最大的消毒灭菌设备...
2003  财经  甘肃陇南地震亲历者口述 在５月１２日四川大地震中，甘肃省部分地市灾情严重，当地居民生活、经济...
2004  财经  深圳：一个“离经叛道”的楼市样本 张艳红编者按由于目前各地楼市处于不同的发展周期，且地缘文化...

In [168]:
# 载入停用词
stopwords = set()
with open('/content/drive/MyDrive/Colab Notebooks/data/stopwords.txt', 'r') as infile:
  for line in infile:
    line = line.rstrip('\n')
    if line:
      stopwords.add(line.lower())

## 2. 计算tfidf

In [169]:
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer

# min_df 去掉df值最小的词
# max_df 去掉df值很大的词
# norm 表示对TF-IDF矩阵的每一行使用l2范数正则化(变成单位向量 模长为1)   l1范数就是绝对值的和   max正则化---最大值
# use_idf: 表示在TF矩阵的基础上计算IDF，并相乘得到TF-IDF
# smooth_idf: 表示计算IDF时，分子上的总文档数+1
# sublinear_tf: 表示使用 1+log(tf)替换原来的tf
tfidf = TfidfVectorizer(tokenizer=jieba.lcut, stop_words=stopwords, min_df=0.1, max_df=0.6, norm='l2', use_idf=True, smooth_idf=False, sublinear_tf=False)
x = tfidf.fit_transform(train_data[u'内容'])

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['&', ',', '.', ';', 'e', 'g', 'nbsp', '—', '\u3000', '傥', '兼', '前', '唷', '啪', '啷', '喔', '始', '漫', '然', '特', '竟', '若果', '莫', '见', '设', '说', '达', '非'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [170]:
#返回的是稀疏矩阵
x.toarray()

array([[0.        , 0.        , 0.01670473, ..., 0.04152225, 0.        ,
        0.06108093],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.03749725],
       [0.        , 0.        , 0.22547076, ..., 0.        , 0.        ,
        0.04122175],
       [0.03229787, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [171]:
print(u'词表大小：{}'.format(len(tfidf.vocabulary_)))

词表大小：816


In [172]:
print(tfidf.vocabulary_)

{'ｇ': 798, 'ｒ': 808, 'ｏ': 806, 'ｕ': 811, 'ｐ': 807, 'ｄ': 795, 'ｙ': 815, 'ｎ': 805, 'ｍ': 804, 'ｉ': 800, 'ｃ': 794, 'ｓ': 809, '有着': 493, '世纪': 50, '建议': 345, '地方': 267, '组织': 616, '研究': 584, '后来': 246, '贡献': 690, '商业': 253, '之前': 66, '说': 683, '存在': 297, '创造': 180, 'ｖ': 812, 'ｅ': 796, 'ｔ': 810, 'ｌ': 803, 'ｆ': 797, 'ｈ': 799, '帮助': 335, '今天': 92, '少': 320, '指出': 413, '更加': 475, '环境': 548, '这是': 727, '一种': 16, '不会': 34, '做': 132, '管理': 609, '认为': 677, '作出': 117, '决定': 163, '显然': 471, '缺乏': 631, '／': 792, '巨大': 329, '真正': 579, '了解': 72, '情况': 378, '想': 379, '东西': 53, '世界': 48, '里': 748, '重要': 753, '多年': 284, '严重': 58, '经历': 618, '愿意': 385, '再': 159, '一次': 13, '第一次': 604, '事': 73, '完全': 300, '不同': 37, '个人': 59, '理解': 559, 'ｗ': 813, '为什么': 63, '无法': 456, '喜欢': 254, '最高': 487, '地位': 265, '难': 768, '证明': 682, '什么': 89, '寻找': 314, '知道': 581, '不能': 41, '应该': 343, '冲击': 162, '得到': 366, '不要': 42, '希望': 332, '必须': 368, '解决': 673, '关系': 151, '影响': 360, '非常': 776, '一位': 4, '能够': 652, '实现': 305, '生活': 561,

In [173]:
pd.DataFrame(x.toarray(), columns=[a[0] for a in sorted(tfidf.vocabulary_.items(), key=lambda a: a[1])])

·         —        一下        一份  ...         ｖ         ｗ    ｘ         ｙ
0     0.000000  0.000000  0.016705  0.000000  ...  0.040630  0.041522  0.0  0.061081
1     0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.0  0.000000
2     0.000000  0.000000  0.000000  0.000000  ...  0.028353  0.000000  0.0  0.000000
3     0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.0  0.000000
4     0.000000  0.031247  0.000000  0.000000  ...  0.015169  0.000000  0.0  0.000000
...        ...       ...       ...       ...  ...       ...       ...  ...       ...
5995  0.000000  0.000000  0.000000  0.039199  ...  0.000000  0.000000  0.0  0.000000
5996  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.0  0.000000
5997  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.0  0.037497
5998  0.000000  0.000000  0.225471  0.000000  ...  0.146241  0.000000  0.0  0.041222
5999  0.032298  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.0  0.000000

[6000 rows x 816 columns]

In [174]:
pd.DataFrame({'词':[x[0] for x in sorted(tfidf.vocabulary_.items(),key=lambda x:x[1])],'IDF':tfidf.idf_},columns=['词','IDF'])

词       IDF
0     ·  2.716652
1     —  2.447461
2    一下  2.931022
3    一份  3.224082
4    一位  2.468228
..   ..       ...
811   ｕ  2.340047
812   ｖ  2.376344
813   ｗ  2.428506
814   ｘ  3.145581
815   ｙ  2.679324

[816 rows x 2 columns]

## 3. 训练模型

In [175]:
# 编码目标变量 
from sklearn.preprocessing import LabelEncoder
y_encoder = LabelEncoder()
y = y_encoder.fit_transform(train_data[u'分类'])
y

x = tfidf.transform(train_data[u'内容'])
x

<6000x816 sparse matrix of type '<class 'numpy.float64'>'
	with 955277 stored elements in Compressed Sparse Row format>

In [176]:
# 划分训练集
from sklearn.model_selection import train_test_split
train_idx, valid_idx = train_test_split(range(len(y)), test_size=0.3, stratify=y)
train_x = x[train_idx, :]
train_y = y[train_idx]
valid_x = x[valid_idx, :]
valid_y = y[valid_idx]

In [177]:
# 训练贝叶斯模型

from sklearn import naive_bayes, metrics


model_nb = naive_bayes.MultinomialNB()
model_nb.fit(train_x, train_y)
pred_y = model_nb.predict(valid_x)
micro_f1 = metrics.f1_score(valid_y, pred_y, average='micro')
macro_f1 = metrics.f1_score(valid_y, pred_y, average='macro')

print('micro f1:',micro_f1)
print('macro f1:',macro_f1)


micro f1: 0.8988888888888888
macro f1: 0.8991475276584856


## 4. 评价指标

In [178]:
from sklearn.metrics import precision_recall_fscore_support


precision_recall_fscore_support(valid_y, pred_y)

(array([0.96768707, 0.86143573, 0.86949429]),
 array([0.94833333, 0.86      , 0.88833333]),
 array([0.95791246, 0.86071726, 0.87881286]),
 array([600, 600, 600]))

In [179]:
# 计算各项评价指标
def eval_model(y_true, y_pred, labels):
    # 计算每个分类的Precision, Recall, f1, support
    p, r, f1, s = precision_recall_fscore_support(y_true, y_pred)
    # 计算总体的平均Precision, Recall, f1, support
    tot_p = np.average(p, weights=s)
    tot_r = np.average(r, weights=s)
    tot_f1 = np.average(f1, weights=s)
    tot_s = np.sum(s)
    res1 = pd.DataFrame({
        u'Label': labels,
        u'Precision': p,
        u'Recall': r,
        u'F1': f1,
        u'Support': s
    })
    res2 = pd.DataFrame({
        u'Label': [u'总体'],
        u'Precision': [tot_p],
        u'Recall': [tot_r],
        u'F1': [tot_f1],
        u'Support': [tot_s]
    })
    res2.index = [4]
    res = pd.concat([res1, res2])
    return res[[u'Label', u'Precision', u'Recall', u'F1', u'Support']]

In [180]:
eval_model(valid_y, pred_y, y_encoder.classes_)

Label  Precision    Recall        F1  Support
0    体育   0.967687  0.948333  0.957912      600
1    科技   0.861436  0.860000  0.860717      600
2    财经   0.869494  0.888333  0.878813      600
4    总体   0.899539  0.898889  0.899148     1800

In [181]:
precision_recall_fscore_support(valid_y, pred_y,  average='macro')

(0.8995390304718288, 0.898888888888889, 0.8991475276584856, None)

In [182]:
from sklearn.metrics import confusion_matrix

# 计算验证集的混淆矩阵
pd.DataFrame(confusion_matrix(valid_y, pred_y), columns=y_encoder.classes_, index=y_encoder.classes_)

体育   科技   财经
体育  569   22    9
科技   13  516   71
财经    6   61  533

In [183]:
# 计算各项评价指标
arr = precision_recall_fscore_support(valid_y, pred_y)
arr
#df = pd.DataFrame(arr, index=[0,1,2], columns=['Precision', 'Recall', 'F1', 'Support'])
#df

(array([0.96768707, 0.86143573, 0.86949429]),
 array([0.94833333, 0.86      , 0.88833333]),
 array([0.95791246, 0.86071726, 0.87881286]),
 array([600, 600, 600]))

In [184]:
type(arr)

tuple

In [185]:
import dill
import pickle
model_file = '/content/drive/MyDrive/Colab Notebooks/model.pkl'
with open(model_file, 'wb') as outfile:
    dill.dump({
        'y_encoder': y_encoder,
        'tfidf': tfidf,
        'nb': model_nb
    }, outfile)

## 4. 保存模型

In [186]:
from sklearn.externals import joblib

joblib.dump(model_nb, '/content/drive/MyDrive/Colab Notebooks/model_nb.pkl')

['/content/drive/MyDrive/Colab Notebooks/model_nb.pkl']

In [187]:
test_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/sohu_test.txt', sep='\t', header=None, dtype=np.str_, encoding='utf8', names=[u'分类', u'内容'])
test_data = test_data.loc[(test_data['分类']=='体育')|(test_data['分类']=='财经')|(test_data['分类']=='科技')]
test_data.head()

分类                                                 内容
1000  财经  发改委解读油电价格上调：不排除继续上涨可能 今天，几乎所有的媒体都在关注一条消息，国家发展和...
1001  财经  利尔化学首次公开发行股票定价发行公告 特别提示利尔化学股份有限公司首次公开发行股票初步询价及...
1002  财经  公共财政受命危难之际 当前，汶川地震受灾地区正处于从全力救援转向恢复重建的关键时期。在这个过...
1003  财经  四任证监会主席把脉２００５中国股市：积极稳妥发展 ２００２年１２月２１日，“积极稳妥发展资本...
1004  财经  ６月２日上海证券交易所上市公司公告 Ｓｈａｎｇｈａｉ分红派息６０００５５　万东医疗　实施２０...

In [188]:
#加载模型
from sklearn.externals import joblib

model = joblib.load('/content/drive/MyDrive/Colab Notebooks/model.pkl')

In [189]:
#对测试集进行预测
#1.转化为词袋表示
test_x = model['tfidf'].transform(test_data[u'内容'])


/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['&', ',', '.', ';', 'e', 'g', 'nbsp', '—', '\u3000', '傥', '兼', '前', '唷', '啪', '啷', '喔', '始', '漫', '然', '特', '竟', '若果', '莫', '见', '设', '说', '达', '非'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [190]:
#2.预测类别
test_y = model['y_encoder'].fit_transform(test_data[u'分类'])


In [191]:
len(test_y)

3000

In [192]:
pred_y = model['nb'].predict(test_x)

In [193]:
len(pred_y)

3000

In [194]:

micro_f1 = metrics.f1_score(test_y, pred_y, average='micro')
macro_f1 = metrics.f1_score(test_y, pred_y, average='macro')

print('micro f1:',micro_f1)
print('macro f1:',macro_f1)

micro f1: 0.8973333333333333
macro f1: 0.8978420930251921


In [195]:
# 计算各项评价指标
def eval_model(y_true, y_pred, labels):
    # 计算每个分类的Precision, Recall, f1, support
    p, r, f1, s = precision_recall_fscore_support(y_true, y_pred)
    # 计算总体的平均Precision, Recall, f1, support
    tot_p = np.average(p, weights=s)
    tot_r = np.average(r, weights=s)
    tot_f1 = np.average(f1, weights=s)
    tot_s = np.sum(s)
    res1 = pd.DataFrame({
        u'Label': labels,
        u'Precision': p,
        u'Recall': r,
        u'F1': f1,
        u'Support': s
    })
    res2 = pd.DataFrame({
        u'Label': [u'总体'],
        u'Precision': [tot_p],
        u'Recall': [tot_r],
        u'F1': [tot_f1],
        u'Support': [tot_s]
    })
    res2.index = [4]
    res = pd.concat([res1, res2])
    return res[[u'Label', u'Precision', u'Recall', u'F1', u'Support']]

In [196]:
eval_model(test_y, pred_y, y_encoder.classes_)

Label  Precision    Recall        F1  Support
0    体育   0.976289  0.947000  0.961421     1000
1    科技   0.846525  0.877000  0.861493     1000
2    财经   0.873239  0.868000  0.870612     1000
4    总体   0.898684  0.897333  0.897842     3000

In [197]:
arr = precision_recall_fscore_support(test_y, pred_y)

In [198]:
arr

(array([0.97628866, 0.8465251 , 0.87323944]),
 array([0.947, 0.877, 0.868]),
 array([0.96142132, 0.86149312, 0.87061184]),
 array([1000, 1000, 1000]))

In [199]:
pd.DataFrame(confusion_matrix(test_y, pred_y), columns=y_encoder.classes_, index=y_encoder.classes_)



体育   科技   财经
体育  947   36   17
科技   14  877  109
财经    9  123  868